#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("quotation.Resource", IsApplication=true)]

namespace quotation
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int cardBackgroundColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cardCornerRadius = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int cardElevation = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int cardMaxElevation = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int cardPreventCornerOverlap = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int cardUseCompatPadding = 2130771979;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f01000d
			public const int contentPadding = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int contentPaddingBottom = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingLeft = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int contentPaddingRight = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int contentPaddingTop = 2130771984;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int layoutManager = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int reverseLayout = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int spanCount = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int stackFromEnd = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0a0006
			public const int accent = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int cardview_dark_background = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int cardview_light_background = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int cardview_shadow_end_color = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int cardview_shadow_start_color = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int primary = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int primaryDark = 2131361797;
			
			// aapt resource value: 0x7f0a0008
			public const int splash_background = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int window_background = 2131361799;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070003
			public const int cardview_compat_inset_shadow = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int cardview_default_elevation = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int cardview_default_radius = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int item_touch_helper_swipe_escape_velocity = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int share = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash_logo = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int LinearLayout1 = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int adjust_height = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int adjust_width = 2131230722;
			
			// aapt resource value: 0x7f080011
			public const int authorLayout = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int authorText = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int categoryLayout = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int categoryText = 2131230736;
			
			// aapt resource value: 0x7f08000b
			public const int category_autocomplete_search = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int contentTextView = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int dailyButton = 2131230732;
			
			// aapt resource value: 0x7f080013
			public const int imageView1 = 2131230739;
			
			// aapt resource value: 0x7f080000
			public const int item_touch_helper_previous_elevation = 2131230720;
			
			// aapt resource value: 0x7f08000d
			public const int listViewCategory = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int listViewDaily = 2131230728;
			
			// aapt resource value: 0x7f080014
			public const int listViewWriter = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int menu_refresh = 2131230741;
			
			// aapt resource value: 0x7f080003
			public const int none = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int progressBar = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int searchBytext = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int txt_view = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int writerTextView = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int ımageView1 = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AutoComplateSearch = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContentCardView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Daily_Activity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main_Activity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ProgressBar = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Row_List_Category = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Row_List_Writer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int splash_screen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Writer_Activity = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int activity_main = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gtm_analytics = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int add_button_text = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int add_textbox_hint = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int author_tab_text = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int category_tab_text = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int checkbox_text = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_unknown_issue = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int menu_refresh = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int mobile_services = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090005
			public const int AppBaseTheme = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int AppTheme = 2131296262;
			
			// aapt resource value: 0x7f090001
			public const int Base_CardView = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int CardView = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int CardView_Dark = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int CardView_Light = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int FsmTheme = 2131296260;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
